#------------------------------------------------------------------------
# Source File Information (DO NOT MODIFY)
# Source ID: 0ac8c0a8-9999-446b-ac24-59c45ed28cc7
# Source File: Active Directory Verify Credentials.psf
#------------------------------------------------------------------------
#region File Recovery Data (DO NOT MODIFY)
<#RecoveryData:
khQAAB+LCAAAAAAABADVWFtv2jAUfp+0/2DlcYqAEMJlgkhcVmlau6LCur1VJjm0Xk2MbKdtpv34
OQlBhFtMB2wVEsrFx9/x+b5zfJz2DXjsCXg0wBIjdSEICzpGtWQZ7vt3CLWvObknAaYXhMJXPAO3
60nyBGhAOHiS8QjdAifTCPU5+BBIgqkozcW0Xd6wTOeb/FR2SEZz6BijSEiYlb6TwGfPonTB+Cz9
N9G2V2aMlThYK1Xin4n6IZUhh04AoeSYmmgYTijxvkA0Zo8QdCaNBnY8p2617BpUmi0DBcqVjjFV
83UHqesrnhvIeyDU58rS6LNAcqaeJY4r14eczYHLaDFFN5Rs5GEKAzKDIHZLDa2byLLb5WxokekV
88FwLxRSoU2fEuXkiPxSBjXbjnGqhUZx3A13x2ILrcfwIg23O9hC8abtpyf1amF4ybC/E/Yuftsu
J+Mz42JVxL702MvJhXEdynko9+lgM06XzMNSoRuuVTVRq7kRnF3EpGAawxe0V5omqlY0xo/x5HPg
w4vhNjaZKqfR1o99L5SSBScP/SSBSfXyWgLsSsNETkubgVVMbR4sS6VfdTPN9/Hg6IxO8k3bmW8C
+mw2VyufUIhtb0BhcRLcG+6Yh6A3xS0RIaYjGVHoYe+xzyjju+1Xs1xVJO8xH8K75Nlach+st3Pl
+hAL8cy4n8T9lYJrqopf3yzEu/S2CqlhlA3vP2BFygdthVYt5+BKUSviO/ZZORLcg59fyN3Kmzz3
azMoRoYchFgzzx6/Fd2orOHx1d/qxtYpIaluViFPqoItzcvBPFziCdCTs0BjlExHh9GQ9F9JiDTr
ZNyhGe4V8TgTbCrRCAcCjeKSp/b7uQ4j+R7hgIqRW6Y29XVLNYhae86SeR2X0h1qpzf/tVSyFHpj
UrH128ncMvWl0jxYKpa2VDJvPmo2E7klHKebOKPE0rPx8mic9ET/Um6lhjOXJhJxc9fpMapTP9YO
M4eJb1sA9LerZkspsX6QErU2t/QYu/7d4nd2rI3ltvdsu0eq2xZcKNv8TVcImCmNgcjGLp5E7kx4
jFMyOYJO2+XlrOsoaWacA+Po2VeMGH/XOg8Qx8/q6PUarIo9daaNqWX5TgXbuBjrx4yeZU19xuH4
QMvbVPLt8uo3SPcPjCEwqJIUAAA=#>
#endregion

<#
    .NOTES
    --------------------------------------------------------------------------------
     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2017 v5.4.134
     Generated on:       15/02/2017 2:41 PM
     Generated by:       
    --------------------------------------------------------------------------------
    .DESCRIPTION
        GUI script generated by PowerShell Studio 2017
#>


#----------------------------------------------
#region Application Functions
#----------------------------------------------

#endregion Application Functions

#----------------------------------------------
# Generated Form Function
#----------------------------------------------
function Show-Active_Directory_Verify_Credentials_psf {

	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	#endregion Import Assemblies

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$formADVerifyCredentials = New-Object 'System.Windows.Forms.Form'
	$Output = New-Object 'System.Windows.Forms.TextBox'
	$buttonVerify = New-Object 'System.Windows.Forms.Button'
	$PasswordText = New-Object 'System.Windows.Forms.TextBox'
	$UsernameText = New-Object 'System.Windows.Forms.TextBox'
	$labelPassword = New-Object 'System.Windows.Forms.Label'
	$labelUsername = New-Object 'System.Windows.Forms.Label'
	$labelActiveDirectoryVerif = New-Object 'System.Windows.Forms.Label'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	# User Generated Script
	#----------------------------------------------
	
	$formADVerifyCredentials_Load={
		#TODO: Initialize Form Controls here
		
	}
	
	$labelActiveDirectoryVerif_Click={
		#TODO: Place custom script here
		
	}
	
	$labelUsername_Click={
		#TODO: Place custom script here
		
	}
	
	$buttonVerify_Click= {
		#TODO: Place custom script here
		
		$WarningPreference = 'SilentlyContinue'
		$ErrorActionPreference = 'SilentlyContinue'
		Function Test-ADAuthentication
		{
			param ($userlogin,
				$userpassword)
			(new-object directoryservices.directoryentry "", $userlogin, $userpassword).psbase.name -ne $null
			
		}
		$login = $UsernameText.Text
		$password = $PasswordText.Text
		if (Test-ADAuthentication $login $password)
		{
			
			$Output.Text = "Correct Password"
		}
		else
		{
			$Output.Text = "Incorrect Password or Username.. Try again"
		}
	}
	
	
	
	
	$PasswordText_TextChanged={
		#TODO: Place custom script here
		
	}
	
	
	$PasswordText_KeyPress = [System.Windows.Forms.KeyPressEventHandler]{
		# This section is used for the Enter Key Press
		
		#Event Argument: $_ = [System.Windows.Forms.KeyPressEventArgs]
		#TODO: Place custom script here
		if ($_.KeyChar -eq 13)
		{
			&$buttonVerify_Click
		}
	}
	
	# --End User Generated Script--
	#----------------------------------------------
	#region Generated Events
	#----------------------------------------------
	
	$Form_StateCorrection_Load=
	{
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$formADVerifyCredentials.WindowState = $InitialFormWindowState
	}
	
	$Form_Cleanup_FormClosed=
	{
		#Remove all event handlers from the controls
		try
		{
			$buttonVerify.remove_Click($buttonVerify_Click)
			$PasswordText.remove_TextChanged($PasswordText_TextChanged)
			$PasswordText.remove_KeyPress($PasswordText_KeyPress)
			$labelUsername.remove_Click($labelUsername_Click)
			$labelActiveDirectoryVerif.remove_Click($labelActiveDirectoryVerif_Click)
			$formADVerifyCredentials.remove_Load($formADVerifyCredentials_Load)
			$formADVerifyCredentials.remove_Load($Form_StateCorrection_Load)
			$formADVerifyCredentials.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch { Out-Null <# Prevent PSScriptAnalyzer warning #> }
	}
	#endregion Generated Events

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$formADVerifyCredentials.SuspendLayout()
	#
	# formADVerifyCredentials
	#
	$formADVerifyCredentials.Controls.Add($Output)
	$formADVerifyCredentials.Controls.Add($buttonVerify)
	$formADVerifyCredentials.Controls.Add($PasswordText)
	$formADVerifyCredentials.Controls.Add($UsernameText)
	$formADVerifyCredentials.Controls.Add($labelPassword)
	$formADVerifyCredentials.Controls.Add($labelUsername)
	$formADVerifyCredentials.Controls.Add($labelActiveDirectoryVerif)
	$formADVerifyCredentials.AutoScaleDimensions = '6, 13'
	$formADVerifyCredentials.AutoScaleMode = 'Font'
	$formADVerifyCredentials.ClientSize = '433, 132'
	$formADVerifyCredentials.Name = 'formADVerifyCredentials'
	$formADVerifyCredentials.Text = 'AD Verify Credentials'
	$formADVerifyCredentials.add_Load($formADVerifyCredentials_Load)
	#
	# Output
	#
	$Output.Location = '12, 98'
	$Output.Name = 'Output'
	$Output.Size = '408, 20'
	$Output.TabIndex = 7
	#
	# buttonVerify
	#
	$buttonVerify.Location = '307, 59'
	$buttonVerify.Name = 'buttonVerify'
	$buttonVerify.Size = '113, 23'
	$buttonVerify.TabIndex = 5
	$buttonVerify.Text = 'Verify'
	$buttonVerify.UseCompatibleTextRendering = $True
	$buttonVerify.UseVisualStyleBackColor = $True
	$buttonVerify.add_Click($buttonVerify_Click)
	#
	# PasswordText
	#
	$PasswordText.Location = '86, 62'
	$PasswordText.Name = 'PasswordText'
	$PasswordText.PasswordChar = '*'
	$PasswordText.Size = '215, 20'
	$PasswordText.TabIndex = 4
	$PasswordText.add_TextChanged($PasswordText_TextChanged)
	$PasswordText.add_KeyPress($PasswordText_KeyPress)
	#
	# UsernameText
	#
	$UsernameText.Location = '86, 33'
	$UsernameText.Name = 'UsernameText'
	$UsernameText.Size = '215, 20'
	$UsernameText.TabIndex = 3
	#
	# labelPassword
	#
	$labelPassword.AutoSize = $True
	$labelPassword.Font = 'Microsoft Sans Serif, 9pt'
	$labelPassword.Location = '12, 62'
	$labelPassword.Name = 'labelPassword'
	$labelPassword.Size = '61, 15'
	$labelPassword.TabIndex = 2
	$labelPassword.Text = 'Password'
	#
	# labelUsername
	#
	$labelUsername.AutoSize = $True
	$labelUsername.Font = 'Microsoft Sans Serif, 9pt'
	$labelUsername.Location = '12, 38'
	$labelUsername.Name = 'labelUsername'
	$labelUsername.Size = '68, 15'
	$labelUsername.TabIndex = 1
	$labelUsername.Text = 'Username:'
	$labelUsername.add_Click($labelUsername_Click)
	#
	# labelActiveDirectoryVerif
	#
	$labelActiveDirectoryVerif.AutoSize = $True
	$labelActiveDirectoryVerif.Font = 'Microsoft Sans Serif, 9.75pt, style=Bold'
	$labelActiveDirectoryVerif.Location = '12, 9'
	$labelActiveDirectoryVerif.Name = 'labelActiveDirectoryVerif'
	$labelActiveDirectoryVerif.Size = '289, 16'
	$labelActiveDirectoryVerif.TabIndex = 0
	$labelActiveDirectoryVerif.Text = 'Active Directory | Verify User Credentials'
	$labelActiveDirectoryVerif.add_Click($labelActiveDirectoryVerif_Click)
	$formADVerifyCredentials.ResumeLayout()
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $formADVerifyCredentials.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$formADVerifyCredentials.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$formADVerifyCredentials.add_FormClosed($Form_Cleanup_FormClosed)
	#Show the Form
	return $formADVerifyCredentials.ShowDialog()

} #End Function

#Call the form
Show-Active_Directory_Verify_Credentials_psf | Out-Null
